# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 16:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('a_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='公告前言')),
                ('a_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='公告内容')),
                ('a_creating', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('a_modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('a_isdelete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': '公告信息',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('m_msg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='留言内容')),
                ('m_image', models.ImageField(blank=True, null=True, upload_to='message/images', verbose_name='上传图片')),
                ('m_creating', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('n_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻概述')),
                ('n_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='新闻内容')),
                ('n_creating', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('n_isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '新闻信息',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=100, verbose_name='帖子标题')),
                ('p_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='发帖内容')),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='post/images', verbose_name='上传图片')),
                ('p_file', models.FileField(blank=True, null=True, upload_to='post/files', verbose_name='上传文件')),
                ('p_creating', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('p_isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '论坛',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.ImageField(blank=True, null=True, upload_to='heads', verbose_name='用户头像')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('education', models.CharField(blank=True, max_length=10, null=True, verbose_name='学历')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('hobby', models.CharField(blank=True, max_length=50, null=True, verbose_name='兴趣')),
                ('signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='个性签名')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='公司')),
                ('profession', models.CharField(blank=True, max_length=20, null=True, verbose_name='职业')),
                ('position', models.CharField(blank=True, max_length=20, null=True, verbose_name='职位')),
                ('income', models.CharField(blank=True, max_length=20, null=True, verbose_name='收入')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='家庭地址')),
                ('mobile', models.CharField(blank=True, max_length=11, unique=True, verbose_name='手机号')),
                ('qq', models.CharField(blank=True, max_length=10, unique=True, verbose_name='QQ号')),
                ('password', models.CharField(max_length=16, verbose_name='用户密码')),
                ('creating', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post', verbose_name='帖子'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='用户'),
        ),
    ]
